### ISSUE TITLE
Parsing with tab character throws 

### ISSUE THREAD

**Issue by matthiasg** [jshttp/content-disposition#12]
not sure whether this shoulld be supported per spec but i get emails with the following content disposition:

`attachment;\tfilename="Saturn_V__-_Kennedy_Space_Center_MyUglyPhotos.com_FullSize.jpg"`

note the \t instead of a space. this seems unsupported. when i replace the tab with space it works fine.

**Comment by dougwilson** [comment]
Hi @matthiasg yes this is a bug! I'm working to fix it now. We should be parsing with ABNF LWS for the separators, which includes the horizontal character. Instead right now it's only accepting the space character.

**Comment by dougwilson** [comment]
The fix has been published to npm as version 0.5.2, enjoy!

**Comment by matthiasg** [comment]
thx :)
