### ISSUE TITLE
Filename with square brackets throws exception

### ISSUE THREAD

**Issue by Borewit** [jshttp/content-disposition#17]
The following header cannot be parsed: `"Attachment; filename=[torrent.cd].Big_Buck_Bunny_1080p.torrent"`

**Comment by dougwilson** [comment]
Yes, that is correct. The square brackets mean the filename must be quoted according to https://tools.ietf.org/html/rfc6266

**Comment by Borewit** [comment]
Thx, apparently my web browser is more tolerant for malformed headers

**Comment by dougwilson** [comment]
Looking at the test suite for the RFC, it seems most browsers will accept it. http://greenbytes.de/tech/tc2231/#attfnbrokentoken

**Comment by Borewit** [comment]
Interesting, that is well documented. 
So the question is, how strict do you want the parser to be?
