### ISSUE TITLE
filename* is not supported

### ISSUE THREAD

**Issue by tiholic** [jshttp/content-disposition#28]
![image](https://user-images.githubusercontent.com/14252381/68427833-eb41ba00-01d0-11ea-824e-23878a96c4a5.png)
Highlighted part is not handled in parsing!

**Comment by dougwilson** [comment]
AFAIK it is. Can you provide code that shows it not working for you?

**Comment by dougwilson** [comment]
```
$ node -pe "require('content-disposition').parse('attachment; filename*=UTF-8\'\'foo')"
ContentDisposition {
  type: 'attachment',
  parameters: { filename: 'foo' }
}
```
