### ISSUE TITLE
filename not support chinese is become `????.epub`

### ISSUE THREAD

**Issue by bluelovers** [jshttp/content-disposition#30]
```json
  http_filename: '小說名字.epub',
  attachment: `attachment; filename="????.epub"; filename*=UTF-8''%E5%B0%8F%E8%AA%AA%E5%90%8D%E5%AD%97.epub`
```

**Comment by dougwilson** [comment]
Hi @bluelovers the `filename` parameter in the header can only be made up of ASCII characters following the specification: https://tools.ietf.org/html/rfc6266

You can add the option `{ fallback: false }` to not generate the `filename` parameter and only keep the `filenme*` parameter (https://github.com/jshttp/content-disposition#fallback).

**Comment by bluelovers** [comment]
i think maybe should encode it too when it is has not allow char, not  make it become `????`

**Comment by dougwilson** [comment]
Hi @bluelovers the `filename` parameter cannot be encoded, unfortunately, only the `filename*` can. You can read more in the specification: https://tools.ietf.org/html/rfc6266
