### ISSUE TITLE
Usage in browser. path and safe-buffer modules

### ISSUE THREAD

**Issue by denis111** [jshttp/content-disposition#32]
Can't use it in browser...
Module not found: Error: Can't resolve 'path' in 'node_modules/content-disposition'

**Comment by dougwilson** [comment]
This module is built for Node.js

**Comment by MoonStorm** [comment]
If this is not meant to be used in the browser, just say it so in the description of the package!

**Comment by dougwilson** [comment]
Hi @MoonStorm thanks for that. I'll add to the top the standard boilerplate that we use in other jshttp modules that states this is a Node.js module.
