### ISSUE TITLE
Possibly address other control characters in header

### ISSUE THREAD

**Issue by xavdid** [jshttp/content-disposition#36]
When getting a file from an image host (this one, specifically: `https://api.typeform.com/responses/files/021c75a337027977e5a216a97c3a93de77e6706df6ff381f1bce6bc6ad0cc65d/A%CC%88laze.jpg`) the `content-disposition` header is the following:

`attachment; filename=f4f1ac339c07-Ãlaze.jpg`

Note the control character (`\x84`) before `laze`. When passed into `contentDisposition.parse`, an error is thrown.

I'm not sure if this is a bug on the image host's side (likely caused by the non-ASCII `Ã`) or this library (control characters should be allowed in filenames, but aren't). 

If it's a bug here, I'm happy to expand the regex. Otherwise, feel free to close this issue and I'll talk to the server hosts. 

Thank you!

**Comment by dougwilson** [comment]
Yea, it is a bug in the server side. You can refer to the ANBF of the specification for the header linked in the readme for the allowed characters. Outside of ascii you have to encode the header, but it is a common mistake to make to put perhaps raw utf-8 into http headers.

**Comment by xavdid** [comment]
Perfect, thank you!
