### ISSUE TITLE
Will this package ever hit a major version?

### ISSUE THREAD

**Issue by rehanvdm** [jshttp/content-disposition#40]
TIL how complicated encoding this header field could be 😅, man the internet feels broken with times.

It looks like the package was created in 2014, will it hit stable aka a major version anytime soon? What is preventing it from hitting a major version?

**Comment by dougwilson** [comment]
Just hasn't had a breaking change yet since it was first released. When there is a breaking change in a release, we'll publishing with a bumped major number 👍
