### ISSUE TITLE
Throwing an error during parsing 

### ISSUE THREAD

**Issue by hbakhtiyor** [jshttp/content-disposition#9]
if `content-disposition` header only ends with `;`

e.g.
```js
contentDisposition.parse('attachment; filename="foo.bar";');
```

```
TypeError: invalid parameter format
    at Function.parse (/dummy/node_modules/content-disposition/index.js:369:11)
```

also, if not passed `type`

```js
contentDisposition.parse('filename="foo.bar"');
```
```
TypeError: invalid type format
    at Function.parse (/dummy/node_modules/content-disposition/index.js:311:11)
```
I think need to able to parse without `type` too.

version of the lib: `0.5.1`

**Comment by dougwilson** [comment]
Both of those string are invalid `Content-Disposition` HTTP header values! This module purely follows the RFC. You can find information regarding the specification in the references section https://github.com/jshttp/content-disposition/blob/master/README.md#references

The RFC says a trailing semicolon is not valid (and I copied the ABNF you can read into the comments of this module) and also requires the type at the beginning.
